import { useState } from 'react';
import useModalFocus from '../../ui/useModalFocus';
import Icon from '../../ui/Icon';
import { ACTIONS, TRIGGERS } from '../../core/automation';
import { formatDuration } from '../../core/session';
export default function Automations({ focus }) {
  const [editing, setEditing] = useState(null);
  const [draft, setDraft] = useState(null);
  useModalFocus(Boolean(editing), () => setEditing(null));
  const events = [...(focus.live?.events || []), ...focus.sessions.flatMap(s => s.events.map(e => ({ ...e, mode: s.mode })))].slice(0, 20);
  function edit(rule) { setDraft({ ...rule }); setEditing(rule.id); }
  function save(event) { event.preventDefault(); focus.setRules(prev => prev.map(r => r.id === editing ? { ...draft, duration: Number(draft.duration), threshold: Number(draft.threshold), cooldown: Number(draft.cooldown) } : r)); setEditing(null); }
  return <>
    <div className="page-heading"><div className="eyebrow">LESS FRICTION. MORE FLOW.</div><h1>A coach that works your way.</h1><p>Small automations that turn attention signals into thoughtful actions.</p></div>
    <div className="workflow-strip"><div><span>01</span><Icon name="eye"/><strong>Notice a signal</strong></div><Icon name="arrow"/><div><span>02</span><Icon name="clock"/><strong>Wait for a pattern</strong></div><Icon name="arrow"/><div><span>03</span><Icon name="bolt"/><strong>Take a helpful action</strong></div></div>
    <div className="rules-grid">{focus.rules.map((rule, index) => <section className={`panel automation-card ${!rule.enabled ? 'rule-off' : ''}`} key={rule.id}><div className="automation-top"><span className={`automation-symbol symbol-${index}`}><Icon name={['bolt', 'pause', 'clock', 'leaf'][index]} size={24}/></span><button className={`toggle ${rule.enabled ? 'on' : ''}`} role="switch" aria-checked={rule.enabled} aria-label={`Enable ${rule.name}`} onClick={() => focus.setRules(prev => prev.map(r => r.id === rule.id ? { ...r, enabled: !r.enabled } : r))}><span/></button></div><h2>{rule.name}</h2><p>{rule.description}</p><div className="rule-flow"><div><small>WHEN</small><span>{TRIGGERS[rule.trigger]}{['focused', 'distracted'].includes(rule.trigger) ? ` ${rule.threshold}` : ''}</span></div><div><small>{rule.trigger === 'interval' ? 'EVERY' : 'FOR'}</small><span>{formatDuration(rule.duration * 1000)}</span></div><div><small>THEN</small><strong>{ACTIONS[rule.action]}</strong></div></div><div className="automation-bottom"><span><i className={`dot ${rule.enabled ? 'green-dot' : ''}`}/>{rule.enabled ? 'Enabled' : 'Disabled'} · {rule.cooldown}s cooldown</span><button className="text-button" onClick={() => edit(rule)}><Icon name="settings" size={15}/> Configure</button></div></section>)}</div>
    <section className="panel execution-log"><div className="panel-heading"><div><h2>Every action, accounted for</h2><p>Recent automation runs from this browser. Demo runs are labeled.</p></div><Icon name="chart"/></div>{events.length ? <div className="table-scroll"><table><thead><tr><th>Automation</th><th>Action</th><th>Session time</th><th>Source</th></tr></thead><tbody>{events.map(e => <tr key={e.id}><td><strong>{e.title}</strong></td><td>{e.delivery}</td><td>{formatDuration(e.elapsed)}</td><td><span className="badge">{e.mode || focus.live?.mode || 'camera'}</span></td></tr>)}</tbody></table></div> : <div className="empty-state compact"><Icon name="bolt" size={30}/><h3>Ready for your first little win.</h3><p>Start a session or demo. Rules run automatically when their conditions are met.</p></div>}</section>
    <div className="bottom-note"><Icon name="info" size={14}/> Automations run during active sessions while this tab is visible. Pausing resets continuous trigger timers.</div>
    {editing && <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setEditing(null); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="rule-title"><div className="panel-heading"><h2 id="rule-title">{draft.name}</h2><button className="icon-button" aria-label="Close rule editor" onClick={() => setEditing(null)}><Icon name="close"/></button></div><form onSubmit={save}><label>Trigger<span className="readonly-field">{TRIGGERS[draft.trigger]}</span></label>{['distracted', 'focused'].includes(draft.trigger) && <label>Focus score threshold<input autoFocus type="number" min="0" max="100" required value={draft.threshold} onChange={e => setDraft({ ...draft, threshold: e.target.value })}/></label>}<label>{draft.trigger === 'interval' ? 'Repeat every (seconds)' : 'Condition must hold for (seconds)'}<input type="number" min="1" max="7200" required value={draft.duration} onChange={e => setDraft({ ...draft, duration: e.target.value })}/></label><label>Action<select value={draft.action} onChange={e => setDraft({ ...draft, action: e.target.value })}>{Object.entries(ACTIONS).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>Minimum time between runs (seconds)<input type="number" min="1" max="3600" required value={draft.cooldown} onChange={e => setDraft({ ...draft, cooldown: e.target.value })}/></label><p className="form-hint">Desktop notifications require permission in Settings. Without it, you’ll still receive an in-app coach card.</p><button className="button button-primary full" type="submit">Save automation <Icon name="check" size={16}/></button></form></section></div>}
  </>;
}
