import { useState } from 'react';
import Icon from '../../ui/Icon';
import Chart from '../../ui/Chart';
import { formatDuration, download, exportSession } from '../../core/session';
export default function Reports({ focus, navigate }) {
  const [filter, setFilter] = useState('all');
  const sessions = focus.sessions.filter(s => filter === 'all' || s.mode === filter);
  const selected = sessions.find(s => s.id === focus.selectedReport) || sessions[0];
  const total = sessions.reduce((n, s) => n + s.elapsed, 0);
  const focused = sessions.reduce((n, s) => n + s.focusedMs, 0);
  const actions = sessions.reduce((n, s) => n + s.events.length, 0);
  const average = sessions.length ? Math.round(sessions.reduce((n, s) => n + s.average, 0) / sessions.length) : null;
  function exportAll() { download('attn-session-reports.json', JSON.stringify({ version: 2, exportedAt: new Date().toISOString(), sessions }, null, 2)); }
  return <>
    <div className="page-heading heading-with-action"><div><div className="eyebrow">PROGRESS, WITH PERSPECTIVE</div><h1>Your focus has a story.</h1><p>Find your patterns. Celebrate your progress. Make tomorrow a little better.</p></div><button className="button button-white" disabled={!sessions.length} onClick={exportAll}><Icon name="download" size={16}/> Export reports</button></div>
    <div className="report-filter"><div className="segmented">{[['all', 'All sessions'], ['camera', 'My sessions'], ['demo', 'Demo sessions']].map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label}</button>)}</div><span>Stored only in this browser · {sessions.length} sessions</span></div>
    <div className="stats-grid">{[['clock', 'Intentional time', formatDuration(total), `${sessions.length} completed sessions`], ['eye', 'Average signal', average === null ? '—' : `${average}%`, 'Average of session averages'], ['leaf', 'Focused time', formatDuration(focused), 'Observed signal of 65 or higher'], ['bolt', 'Helpful actions', actions, 'Automations put to work']].map(([icon, label, value, note]) => <section className="panel stat-card" key={label}><div><span>{label}</span><Icon name={icon} size={18}/></div><strong>{value}</strong><small>{note}</small></section>)}</div>
    {!sessions.length ? <section className="panel empty-state report-empty"><span className="empty-icon"><Icon name="chart" size={36}/></span><h2>Every good story starts somewhere.</h2><p>Finish your first focus session to see your rhythm, coach activity, and a little perspective on your day.</p><button className="button button-primary" onClick={() => navigate('focus')}>Make a little space <Icon name="arrow" size={16}/></button></section> : <div className="reports-grid"><section className="panel session-history"><div className="panel-heading"><h2>Your sessions</h2><span className="badge">Latest {sessions.length}</span></div>{sessions.map(s => <button className={`history-item ${selected?.id === s.id ? 'selected' : ''}`} key={s.id} onClick={() => focus.setSelectedReport(s.id)}><span className="history-icon"><Icon name={s.mode === 'demo' ? 'play' : 'leaf'} size={19}/></span><span><strong>{s.title}</strong><small>{new Date(s.startedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} · {formatDuration(s.elapsed)} {s.mode === 'demo' ? '· DEMO' : ''}</small></span><b>{s.average}<small>/100</small></b></button>)}</section><section className="panel report-detail"><div className="panel-heading"><div><span className="eyebrow">{selected.mode === 'demo' ? 'SIMULATED SESSION REPORT' : 'PERSONAL SESSION REPORT'}</span><h2>{selected.title}</h2></div><Icon name="leaf"/></div><div className="report-summary"><div><strong>{selected.focusPercent}%</strong><span>of time in focus</span></div><div><strong>{formatDuration(selected.longestStreak || 0)}</strong><span>longest focus streak</span></div><div><strong>{selected.events.length}</strong><span>coach actions</span></div></div><Chart samples={selected.samples} height={170}/><div className="chart-footer"><span>Start</span><span>{formatDuration(selected.elapsed)}</span></div><div className="report-insight"><Icon name="leaf" size={22}/><div><strong>{selected.focusPercent >= 70 ? 'You found a good rhythm.' : 'Showing up is a good start.'}</strong><p>{selected.focusPercent >= 70 ? 'Your visual attention cues were steady for most of this session. Notice what helped you settle in.' : 'Try one smaller task, fewer open tabs, or a shorter session next time. There is no perfect score to chase.'}</p></div></div><div className="report-actions"><button className="button button-white" onClick={() => download(`attn-${selected.id.slice(0, 8)}.csv`, exportSession(selected), 'text/csv')}><Icon name="download" size={16}/> Download timeline</button><span>{selected.reason === 'goal' ? 'Goal completed automatically' : 'Ended by you'}</span></div></section></div>}
  </>;
}
